name: MD

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Select an environment'
        required: true
        type: choice
        options:
          - aks-alpha-fint-2021-11-18
          - aks-beta-fint-2021-11-23
          - aks-api-fint-2022-02-08
      org:
        description: 'Select organisation'
        required: true
        type: choice
        options:
          - fintlabs-no

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CLUSTER_NAME: ${{ inputs.cluster }}
  ORG: ${{ inputs.org }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    concurrency:
      group: manual-deploy-${{ inputs.cluster }}-${{ inputs.org }}
      cancel-in-progress: false
    steps:
      - name: Determine resource group
        id: rg
        uses: actions/github-script@v7
        with:
          script: |
            const p='${{ inputs.cluster }}'.split('-'); return `rg-${p[0]}-${p[1]}`;
          result-encoding: string
      - name: Determine env key
        id: environment
        uses: actions/github-script@v7
        with:
          script: return '${{ inputs.cluster }}'.split('-')[1];
          result-encoding: string
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - uses: gradle/actions/wrapper-validation@v5
      - uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: wrapper
      - name: build gradlew
        run: ./gradlew -x test build

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - id: bake
        uses: azure/k8s-bake@v3
        with:
          renderEngine: 'kustomize'
          kustomizationPath: kustomize/overlays/${{ steps.environment.outputs.result }}
      - name: Determine secret name
        id: secretname
        run: |
          echo "SECRET_NAME=$(echo AKS_${{ steps.environment.outputs.result }}_FINT_GITHUB | tr '[:lower:]' '[:upper:]')" >> $GITHUB_OUTPUT
      - uses: azure/login@v2
        with:
          creds: ${{ secrets[ steps.secretname.outputs.SECRET_NAME ] }}
      - uses: azure/aks-set-context@v4
        with:
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ steps.rg.outputs.result }}
          admin: true
          use-kubelogin: true
      - uses: azure/k8s-deploy@v5.0.3
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ steps.meta.outputs.tags }}
          namespace: ${{ env.ORG }}